services:
  #New nest projects
  backend-users:
    container_name: backend-users
    build:
      context: ./backend/users
      dockerfile: Dockerfile
    ports:
      - 3001:3000
    volumes:
      - ./backend/users:/app
    depends_on:
      - mongodb
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_USER=duodinamico
      - MONGO_PASSWORD=1310
      - MONGO_DATABASE=users
    networks:
      - network-software2

  frontend-software2:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 4200:4200
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on: #New nest projects
      - backend-users
    networks:
      - network-software2

  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=duodinamico
      - MONGO_INITDB_ROOT_PASSWORD=1310
    networks:
      - network-software2
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:

networks:
  network-software2: